#!/usr/bin/env bash
# -*- coding: utf-8 -*-
# Author: graypawn (choi.pawn @gmail.com)
# Created: 2017-04-09

# This script is Emergency avoidance utility
# dependence: wmctrl
current_mode="$(wmctrl -m | grep 'showing the desktop')"

# Toggle desktop
if [[ "${current_mode##* }" == ON ]]; then
    wmctrl -k off
else
    wmctrl -k on
fi

pactl set-sink-mute @DEFAULT_SINK@ toggle # Mute
xfce4-terminal --drop-down                # Dummy
