#!/usr/bin/env bash
# -*- coding: utf-8 -*-
# Author: graypawn (choi.pawn @gmail.com)
# Created: 2017-04-24

# TODO: firefox는 여러 탭들이 단일 프로세서로 구성되어 있어. 한 개의 PID만을 갇는다.
# 현재의 'get_index'은 PID의 같이 동일한 SINK_INPUT이 여럿 존재한다면, 먼저 찾은 인덱스를 반환한다.
# 따라서 다음의 3가지 중 1가지를 수행하려 한다.
# 1. PID가 동일한 SINK_INPUT에 모두 동일 작업을 수행한다.
# 2. 선택할 수 있도록 한다. (volume control을 여는 것이...)
# 3. PID 외의 방법으로 SINK_INPUT을 구분한다. (list_sink_input으로는 구분 불가능)

get_window_pid() {
    echo $(xprop -id `xdotool getwindowfocus` | grep '_NET_WM_PID' | grep -oE '[[:digit:]]*$')
}

get_index() {
    local pid=`get_window_pid`
    if [[ -z "$pid" ]]; then
        echo "error: no running processes for: $1" >&2
    else
        pacmd list-sink-inputs |
            awk -v pid=$pid '
            $1 == "index:" {idx = $2}
            $1 == "application.process.id" && $3 == "\"" pid "\"" {print idx; exit}
        '
    fi
}

pactl set-sink-input-mute `get_index` toggle
